import '@/styles/global.scss';

import clsx from 'clsx';

import { pretendardFont, notoSerifFont, notoSansKr } from './fonts';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html
      lang="ko"
      className={clsx(
        pretendardFont.variable,
        notoSerifFont.variable,
        notoSansKr.variable
      )}
    >
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
